name: Build Kernel CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
    - name: Build Kernel
      uses: actions/checkout@v2
      run: |
        ./make.sh
    - uses: actions/upload-artifact@v1
      with:
        name: linux-amlogic
        path: /github/workflow/linux-amlogic/*.pkg.tar.zst