name: Build linux-amlogic
on: [push, pull_request]

jobs:
  linux-amlogic:
    env:
      BUILD_DIR: /tmp/${{ github.job }}
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel-20201129.0.10056
    steps:
    - uses: actions/checkout@v2
    
    #- name: Update packages
    #  run: yes | pacman -Syu --noconfirm

    - name: Install need packages
      run: yes | pacman -Syu --noconfirm --needed base-devel aarch64-linux-gnu-gcc glibc xmlto docbook-xsl kmod inetutils bc git uboot-tools dtc
      
    - name: Add user
      run: |
        useradd -m -G wheel -s /bin/bash builder
        echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
      
    - name: Copy Files
      run: |
        cp -r "$GITHUB_WORKSPACE" "${{ env.BUILD_DIR }}"
        chown builder:builder "${{ env.BUILD_DIR }}"
    
    - name: Make
      run: |
        cd "${{ env.BUILD_DIR }}/linux-amlogic"
        sudo -u builder env \
        ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- KBUILD_BUILD_HOST=github KBUILD_BUILD_USER=${{ github.repository_owner }} \
        makepkg --syncdeps --noconfirm --config ../makepkg.conf
    
    - name: List Files
      run: ls -l ${{ env.BUILD_DIR }}
    
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.job }}
        path: ${{ env.BUILD_DIR }}/*.pkg.tar.zst

